organization: true

# site title
title: IRcloud‘s Blog

# github user
user: 77ircloud 

# issue repository
repository: blog

# multi-author
authors: cisen,大M,Maxxxz,Bobo,Ashen,lounj,Pines-Cheng

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 58a9#80d14cadc76fc741b473987bbbee24e62457

# posts per page
perpage: 10


